version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  test:
    machine: 
      image: ubuntu-2004:202010-01
    steps:
      - run: ls -a
      - run: npm install
      - run: npm test
workflows:
  node-tests:
    jobs:
      - test
