version: 2.1
jobs:
  build: 
    docker:     
      - image: cimg/node:15.14.0
    steps:
      - checkout
      - run:
          name: Installing packages
          command: cd software/frontend && npm ci
      - run:
          name: Running tests
          command: cd software/frontend && npm test